# Generated by Django 4.1.5 on 2023-01-17 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bloco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=15, unique=True)),
                ('legenda', models.TextField()),
                ('imagem', models.ImageField(upload_to='blocos/')),
            ],
        ),
        migrations.CreateModel(
            name='Piso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=15, unique=True)),
                ('bloco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacos.bloco')),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=15, unique=True)),
                ('legenda', models.TextField()),
                ('imagem', models.ImageField(upload_to='salas/')),
                ('piso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacos.piso')),
            ],
        ),
    ]
