# Generated by Django 3.2.8 on 2023-01-31 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacos', '0002_sala_img_360'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='imagem',
            field=models.ImageField(upload_to='salas/', verbose_name='Thumbnail'),
        ),
    ]
