# Generated by Django 3.2.8 on 2023-01-31 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('espacos', '0003_alter_sala_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_cad', models.DateField(auto_now=True)),
                ('comentario', models.TextField()),
                ('nota', models.PositiveIntegerField()),
                ('nome', models.TextField()),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacos.sala')),
            ],
        ),
    ]
